In [38]:
import pandas as pd 
import numpy as np
from transposecsv import Transpose
import os

In [39]:
rand = np.random.rand(500, 1000)
rand = pd.DataFrame(rand)

rand.to_csv('test.csv', index=False)
df = pd.read_csv('test.csv')

In [40]:
df

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,0.616705,0.334028,0.835883,0.600477,0.756304,0.480466,0.454452,0.613654,0.980647,0.160417,...,0.901692,0.411229,0.590878,0.033678,0.283183,0.648352,0.547124,0.834188,0.562644,0.580715
1,0.067559,0.156845,0.434725,0.543312,0.243937,0.049903,0.504564,0.461392,0.765719,0.658038,...,0.551571,0.859963,0.345088,0.937825,0.412965,0.236643,0.835705,0.988965,0.844455,0.854074
2,0.348736,0.414367,0.676563,0.045921,0.053691,0.517365,0.101455,0.905468,0.600793,0.600414,...,0.927304,0.361474,0.110962,0.669105,0.291922,0.897870,0.498963,0.766678,0.030082,0.705906
3,0.501255,0.568353,0.702696,0.075022,0.000182,0.618331,0.264393,0.569823,0.632693,0.587392,...,0.867496,0.282538,0.375796,0.390089,0.931311,0.993715,0.472045,0.123192,0.754894,0.430859
4,0.291966,0.281676,0.824722,0.459605,0.139149,0.801004,0.606684,0.105737,0.005987,0.223492,...,0.809493,0.607565,0.561925,0.834641,0.441083,0.379584,0.550290,0.533934,0.657450,0.955141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0.000411,0.323739,0.790281,0.617444,0.441330,0.952770,0.449099,0.254895,0.037740,0.496682,...,0.289681,0.809734,0.477232,0.798706,0.443306,0.994622,0.322521,0.736076,0.819161,0.794502
496,0.641874,0.283637,0.529887,0.039753,0.065144,0.612803,0.420885,0.681530,0.509790,0.763186,...,0.298012,0.290038,0.088563,0.221714,0.355800,0.729429,0.671680,0.777011,0.765838,0.830432
497,0.854970,0.033193,0.031026,0.916984,0.785021,0.407730,0.237508,0.843360,0.951692,0.647840,...,0.886470,0.878625,0.886377,0.474368,0.382736,0.243933,0.214466,0.900930,0.024525,0.129652
498,0.790144,0.013893,0.202554,0.676615,0.120588,0.973387,0.805121,0.236526,0.262662,0.591740,...,0.169648,0.200093,0.006531,0.585262,0.873663,0.547918,0.267307,0.864610,0.891856,0.365790
499,0.961225,0.741222,0.055370,0.821745,0.403913,0.713994,0.271804,0.410217,0.967857,0.612112,...,0.126360,0.394410,0.854956,0.103282,0.248028,0.076940,0.393959,0.377196,0.434118,0.139663

In [41]:
trans = Transpose('test.csv', 'test_T.csv')
trans.compute()

Number of lines to process is 500
Total number of chunks is 1
Working on chunk 0 out of 1
Writing chunk 0 to csv
Working on chunk 1 out of 1
Writing chunk 1 to csv
Combining chunks from chunks_test_T into test_T.csv
Finished combining chunks, deleting chunks.
Done.

In [42]:
trans = pd.read_csv('test_T.csv')
trans.head()

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,0.616705,0.067559,0.348736,0.501255,0.291966,0.934479,0.292764,0.349458,0.803709,0.010797,...,0.399559,0.184723,0.198125,0.076746,0.786381,0.000411,0.641874,0.854970,0.790144,0.961225
1,0.334028,0.156845,0.414367,0.568353,0.281676,0.103137,0.315980,0.097411,0.113822,0.246949,...,0.773446,0.286520,0.972754,0.626076,0.116148,0.323739,0.283637,0.033193,0.013893,0.741222
2,0.835883,0.434725,0.676563,0.702696,0.824722,0.788576,0.374569,0.372384,0.934778,0.433912,...,0.973774,0.811549,0.531640,0.954148,0.977117,0.790281,0.529887,0.031026,0.202554,0.055370
3,0.600477,0.543312,0.045921,0.075022,0.459605,0.322511,0.315262,0.804052,0.396454,0.963314,...,0.771313,0.129373,0.314940,0.987313,0.139016,0.617444,0.039753,0.916984,0.676615,0.821745
4,0.756304,0.243937,0.053691,0.000182,0.139149,0.925528,0.227617,0.101667,0.976273,0.911433,...,0.558872,0.196362,0.032643,0.841652,0.972081,0.441330,0.065144,0.785021,0.120588,0.403913

In [43]:
trans.shape, df.shape

((1000, 500), (500, 1000))

In [44]:
df_T = df.T.reset_index(drop=True)

In [18]:
trans

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,0.627377,0.828520,0.335704,0.768965,0.783939,0.436374,0.002934,0.041936,0.702988,0.793758,...,0.947337,0.466716,0.948435,0.365660,0.857305,0.593858,0.787203,0.881848,0.944397,0.335666
1,0.685905,0.754622,0.459188,0.994750,0.596375,0.623746,0.613439,0.660420,0.225121,0.491151,...,0.650693,0.320000,0.742742,0.515064,0.467397,0.572025,0.100184,0.408363,0.036584,0.277451
2,0.278065,0.226524,0.080498,0.013650,0.646726,0.268642,0.163883,0.951548,0.258311,0.222553,...,0.335255,0.160271,0.024644,0.974809,0.138529,0.333356,0.793761,0.884876,0.904330,0.684124
3,0.716675,0.465926,0.604046,0.511252,0.766648,0.317577,0.592836,0.439050,0.217949,0.176332,...,0.525206,0.060007,0.342276,0.709576,0.889903,0.054568,0.368586,0.391648,0.333016,0.803785
4,0.009172,0.626731,0.257232,0.025288,0.422373,0.534870,0.405145,0.216749,0.424042,0.679681,...,0.198287,0.538819,0.480466,0.591463,0.617778,0.580325,0.171375,0.666321,0.888555,0.017107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.929121,0.414575,0.284096,0.541651,0.950396,0.723350,0.255843,0.969389,0.994919,0.371576,...,0.684548,0.170334,0.132176,0.873085,0.157333,0.625890,0.509295,0.840271,0.163347,0.858990
996,0.239641,0.534546,0.463603,0.066235,0.986652,0.321939,0.605148,0.285165,0.275321,0.051958,...,0.462692,0.849984,0.470441,0.768588,0.825115,0.825655,0.803999,0.011924,0.618501,0.139927
997,0.567553,0.796640,0.514111,0.435444,0.485863,0.278454,0.875634,0.585898,0.292187,0.617536,...,0.979276,0.022985,0.519990,0.562954,0.896860,0.044646,0.033325,0.159705,0.311324,0.767365
998,0.748053,0.409848,0.979495,0.450571,0.446074,0.857813,0.240271,0.074816,0.844121,0.416550,...,0.243099,0.381264,0.366749,0.964741,0.622308,0.732461,0.431905,0.150396,0.957666,0.943314
999,0.975571,0.062701,0.799656,0.175946,0.299264,0.642217,0.648031,0.790539,0.867455,0.440225,...,0.740031,0.523544,0.927477,0.102252,0.021845,0.653400,0.493576,0.471660,0.398515,0.260434

In [19]:
df_T

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,0.627377,0.828520,0.335704,0.768965,0.783939,0.436374,0.002934,0.041936,0.702988,0.793758,...,0.947337,0.466716,0.948435,0.365660,0.857305,0.593858,0.787203,0.881848,0.944397,0.335666
1,0.685905,0.754622,0.459188,0.994750,0.596375,0.623746,0.613439,0.660420,0.225121,0.491151,...,0.650693,0.320000,0.742742,0.515064,0.467397,0.572025,0.100184,0.408363,0.036584,0.277451
2,0.278065,0.226524,0.080498,0.013650,0.646726,0.268642,0.163883,0.951548,0.258311,0.222553,...,0.335255,0.160271,0.024644,0.974809,0.138529,0.333356,0.793761,0.884876,0.904330,0.684124
3,0.716675,0.465926,0.604046,0.511252,0.766648,0.317577,0.592836,0.439050,0.217949,0.176332,...,0.525206,0.060007,0.342276,0.709576,0.889903,0.054568,0.368586,0.391648,0.333016,0.803785
4,0.009172,0.626731,0.257232,0.025288,0.422373,0.534870,0.405145,0.216749,0.424042,0.679681,...,0.198287,0.538819,0.480466,0.591463,0.617778,0.580325,0.171375,0.666321,0.888555,0.017107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.929121,0.414575,0.284096,0.541651,0.950396,0.723350,0.255843,0.969389,0.994919,0.371576,...,0.684548,0.170334,0.132176,0.873085,0.157333,0.625890,0.509295,0.840271,0.163347,0.858990
996,0.239641,0.534546,0.463603,0.066235,0.986652,0.321939,0.605148,0.285165,0.275321,0.051958,...,0.462692,0.849984,0.470441,0.768588,0.825115,0.825655,0.803999,0.011924,0.618501,0.139927
997,0.567553,0.796640,0.514111,0.435444,0.485863,0.278454,0.875634,0.585898,0.292187,0.617536,...,0.979276,0.022985,0.519990,0.562954,0.896860,0.044646,0.033325,0.159705,0.311324,0.767365
998,0.748053,0.409848,0.979495,0.450571,0.446074,0.857813,0.240271,0.074816,0.844121,0.416550,...,0.243099,0.381264,0.366749,0.964741,0.622308,0.732461,0.431905,0.150396,0.957666,0.943314
999,0.975571,0.062701,0.799656,0.175946,0.299264,0.642217,0.648031,0.790539,0.867455,0.440225,...,0.740031,0.523544,0.927477,0.102252,0.021845,0.653400,0.493576,0.471660,0.398515,0.260434

In [20]:
df_T.index, trans.index

(RangeIndex(start=0, stop=1000, step=1),
 RangeIndex(start=0, stop=1000, step=1))

In [21]:
all(df_T.dtypes == np.float64), all(trans.dtypes == np.float64)

(True, True)

In [22]:
df_T.columns, trans.columns

(RangeIndex(start=0, stop=500, step=1),
 Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
        ...
        '490', '491', '492', '493', '494', '495', '496', '497', '498', '499'],
       dtype='object', length=500))

In [23]:
trans.columns = pd.RangeIndex(0, len(trans.columns))

In [37]:
(df_T - trans).sum().sum()

-3.3881317890172014e-21

In [35]:
trans - (df_T)

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0